### ISSUE TITLE
Servo not recognised when using dynamixel_control_hw

### ISSUE THREAD

**Issue by bdenoun** [resibots/dynamixel_control_hw#25]
Hi guys,

I installed both libdynamixel and dynamixel_control_hw, and when running my launch file I so have this error message: 
`1 servo was declared to the hardware interface but could not be found`
However when I try it using the command line you provide (`./build/src/tools/dynamixel -p /dev/ttyUSB0 -b 57600 list`) it finds my MX64.
I also changed the communication time to 4 as stated in the doc!
Any ideas why?

**Comment by dogoepp** [comment]
Hi @bdenoun,

Could you share the configuration file you use for this launch file, as well as the ID of the servo you are trying to connect to? I suspect a configuration error.

**Comment by bdenoun** [comment]
Hey,
Here is the configuration file I am using: 

```yaml
dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

dynamixel_robot:
    type: dynamixel/hardware_interface_p1
    serial_interface: /dev/ttyUSB0
    loop_frequency: 500
    baudrate: 57600
    read_timeout: 0.01
    scan_timeout: 0.01
    servos:
        dynamixel_1:
            id: 1
            command_interface: position
    default_command_interface: position
```

Thank you for your help!
